### ISSUE TITLE
Unable to merge epub3

### ISSUE THREAD

**Issue by dmbada** [dteviot/MergeWebToEpub#5]
MergeWebToEpub unable to merge epub3 that is from WebToEpub itself.

I always got this error message while trying to save the epub on MergeWebToEpub.
![error merge](https://user-images.githubusercontent.com/87198532/222351530-a266e7f1-7261-44a3-9126-396e6c330a4e.png)

**Comment by dteviot** [comment]
Did a quick hack to stop the crashing when try saving a Epub3 file created by WebToEpub.
Note, MergeWebToEpub does not properly support Epub3 format.
Because the Epubs generated by WebToEpub have no significant advantages over an Epub2 file, I never use Epub3, and consequently, did not spend time adding support for Epub3.

So, I make no promises about the output of MergeWebToEpub being a valid Epub2 if you give it an Epub3 file.

For my notes: 27 minutes work

**Comment by dmbada** [comment]
Thank you for the update, is it possible for you to update the zip on the drive or tell me how to compile the file?

**Comment by dteviot** [comment]
@dmbada 
D'oh!  Apologies.  Updated zip  "MergeWebToEpub.2023-03-20.zip" has been uploaded to folder https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8.
